url: mqtt://localhost
filter: display/button/+
mappings:
  A:
    - topic: tasmota/cmnd/lounge/light2/power
      payload: toggle
  B: 
    - topic: tasmota/cmnd/lounge/light/power
      payload: toggle
